pushover:
        user: <PUSHOVER_USER_KEY>
        token: <PUSHOVER_API_KEY>

nodes:
        - name: host1
          ip: 10.0.0.1

        - name: host2
          ip: 10.0.0.2

        - name: host3
          ip: 10.0.0.3

